'use strict';

module.exports = {
  WORKSPACE_ALREADY_EXISTS: 'WORKSPACE_ALREADY_EXISTS',
  FORBIDDEN_WORKSPACE_CREATION: 'FORBIDDEN_WORKSPACE_CREATION',
  FORBIDDEN_WORKSPACE_RETRIEVAL: 'FORBIDDEN_WORKSPACE_RETRIEVAL',
  WORKSPACE_ID_NOT_PROVIDED: 'WORKSPACE_ID_NOT_PROVIDED',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  FORBIDDEN_MAILING_RENAME: 'FORBIDDEN_MAILING_RENAME',
  FAILED_MAILING_RENAME: 'FAILED_MAILING_RENAME',
  FORBIDDEN_MAILING_DELETE: 'FORBIDDEN_MAILING_DELETE',
  FAILED_MAILING_DELETE: 'FAILED_MAILING_DELETE',
  FORBIDDEN_MAILING_COPY: 'FORBIDDEN_MAILING_COPY',
  MAILING_MISSING_SOURCE: 'MAILING_MISSING_SOURCE',
  FAILED_MAILING_COPY: 'FAILED_MAILING_COPY',
  FORBIDDEN_MAILING_MOVE: 'FORBIDDEN_MAILING_MOVE',
  FAILED_MAILING_MOVE: 'FAILED_MAILING_MOVE',
  MAILING_NOT_FOUND: 'MAILING_NOT_FOUND'
};
