'use strict';

module.exports = {
  WORKSPACE_ALREADY_EXISTS: 'WORKSPACE_ALREADY_EXISTS',
  FORBIDDEN_WORKSPACE_CREATION: 'FORBIDDEN_WORKSPACE_CREATION',
  FORBIDDEN_WORKSPACE_RETRIEVAL: 'FORBIDDEN_WORKSPACE_RETRIEVAL',
};
