'use strict';

/**
 * The AI icons on the fields an AI action fills (ADR 0004).
 *
 * The subject field has a label row of its own. The preheader field is
 * generated by Mosaico, with no slot per property: its icon goes in the label of
 * the property editor whose input is bound to `preheaderText`, in both template
 * layouts (at the root or in a preheader block, the binding reads the same).
 *
 * Both sections re-render (Vue, Knockout), so this is called again on every
 * change: it places what is missing and never doubles an icon.
 */

const ATTRIBUTE = 'data-ai-target';

const PREHEADER_BINDING = /^\s*value:\s*preheaderText\b/;

// Where each target's icon goes, or null when the field is not on screen.
const ANCHORS = {
  subject: (root) => {
    const label = root.querySelector('label[for="email-metadata-subject"]');
    return label ? label.closest('.email-metadata__label-row') : null;
  },
  preheader: (root) => {
    const input = [...root.querySelectorAll('input[data-bind]')].find(
      (candidate) => PREHEADER_BINDING.test(candidate.getAttribute('data-bind'))
    );
    const editor = input && input.closest('.propEditor');
    return editor ? editor.querySelector('.propLabel') : null;
  },
};

function createIcon(kind, { onOpen, label, anchor }) {
  const icon = document.createElement('button');
  icon.type = 'button';
  icon.className = 'ai-field-icon';
  icon.setAttribute(ATTRIBUTE, kind);
  icon.setAttribute('aria-label', label);
  // A Mosaico property label already shows its own tooltip on hover.
  if (!anchor.closest('[title]')) icon.title = label;
  icon.innerHTML = '<span class="lucide lucide-bot" aria-hidden="true"></span>';
  icon.addEventListener('click', (event) => {
    // The preheader label sits in a property editor that selects on click.
    event.stopPropagation();
    onOpen({ kind });
  });
  return icon;
}

/**
 * @param {Element} root where the fields are looked for
 * @param {{
 *   actionsFor: function({ kind: string }): { actions: Array },
 *   onOpen: function({ kind: string }): void,
 *   labelFor?: function(string): string,
 * }} options
 */
function placeFieldIcons(
  root,
  { actionsFor, onOpen, labelFor = () => 'AI actions' }
) {
  Object.entries(ANCHORS).forEach(([kind, findAnchor]) => {
    const anchor = findAnchor(root);
    if (!anchor) return;
    const existing = anchor.querySelector(`[${ATTRIBUTE}="${kind}"]`);
    const offered = actionsFor({ kind }).actions.length > 0;
    if (!offered) {
      if (existing) existing.remove();
      return;
    }
    if (existing) return;
    const icon = createIcon(kind, { onOpen, label: labelFor(kind), anchor });
    // Right after the field's label, the same for both fields.
    const label = anchor.querySelector('label, span');
    if (label) label.after(icon);
    else anchor.appendChild(icon);
  });
}

module.exports = { placeFieldIcons };
