'use strict';

/**
 * The targets of the AI actions (ADR 0004, amended by #1192): what an action
 * works on, and so where it writes.
 *
 * - `{ kind: 'email' }`: the whole email, the panel with nothing selected;
 * - `{ kind: 'subject' }`, `{ kind: 'preheader' }`: the two copy fields that
 *   live outside the blocks;
 * - `{ kind: 'block', blockId, blockType }`: a block of the canvas;
 * - `{ kind: 'blockField', blockId, blockType, field }`: one field of a block.
 */

const EMAIL = Object.freeze({ kind: 'email' });

/**
 * The target of the canvas selection: a block, or the whole email. The block
 * that holds the preheader is the preheader's target, so the panel offers what
 * the field's icon offers.
 *
 * @param {Object|null} block a Mosaico block (observables `type` and `id`)
 */
function targetOfBlock(block) {
  if (!block) return EMAIL;
  const blockType = block.type();
  if (blockType === 'preheaderBlock') return { kind: 'preheader' };
  return { kind: 'block', blockId: block.id(), blockType };
}

const PREHEADER_BINDING = /^\s*value:\s*preheaderText\b/;

/**
 * The fields that carry an AI icon: where the icon goes (null when the field
 * is not on screen) and what it says.
 */
const FIELD_TARGETS = Object.freeze({
  subject: {
    anchor(root) {
      const label = root.querySelector('label[for="email-metadata-subject"]');
      return label ? label.closest('.email-metadata__label-row') : null;
    },
    labelKey: 'ai-field-subject-label',
  },
  // Generated by Mosaico, with no slot per property: found by the binding of
  // its input (docs/TEMPLATE_DEVELOPER_GUIDE.md, preheader).
  preheader: {
    anchor(root) {
      const input = [...root.querySelectorAll('input[data-bind]')].find(
        (candidate) =>
          PREHEADER_BINDING.test(candidate.getAttribute('data-bind'))
      );
      const editor = input && input.closest('.propEditor');
      return editor ? editor.querySelector('.propLabel') : null;
    },
    labelKey: 'ai-field-preheader-label',
  },
});

module.exports = { EMAIL, targetOfBlock, FIELD_TARGETS };
