version: '3.7'

volumes:
  node_modules:
  mongodb_data:

services:
  database:
    image: mongo:4.2.9
    container_name : badsender_mongo_container
    environment:
      MONGO_INITDB_DATABASE: badsender
      # MONGO_INITDB_ROOT_PASSWORD: user
      # MONGO_INITDB_ROOT_USERNAME: password
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./mongo-volume:/data/db


  # redis:
  #   image: redis:4.0.2-alpine
  # web:
  #   image: badsender/mosaico
  #   build:
  #     context: .
  #   volumes:
  #     - ./mosaico:/home/node/app
  #     - node_modules:/home/node/app/node_modules
  #   environment:
  #     VIRTUAL_PORT: "3000"
  #     VIRTUAL_HOST: "badsender.localhost"
  #   depends_on:
  #     - mongodb
  #     - redis
  smtp:
    image: maildev/maildev
    expose:
      - 1080
      - 80
    environment:
      VIRTUAL_PORT: "80"
      VIRTUAL_HOST: "smtp.badsender.localhost"

# networks:
#   default:
#     external:
#       name: nginx-reverse-proxy
