version: '3.7'

services:
  database:
    image: mongo:4.2.9
    container_name: lepatron_mongo_container
    environment:
      MONGO_INITDB_DATABASE: lepatron
      # MONGO_INITDB_ROOT_PASSWORD: user
      # MONGO_INITDB_ROOT_USERNAME: password
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ../.mongodb:/data/db

  smtp:
    image: maildev/maildev
    expose:
      - 1080
      - 80
    environment:
      VIRTUAL_PORT: '80'
      VIRTUAL_HOST: 'smtp.lepatron.localhost'
