'use strict'

const EVENT_START = `START`
const EVENT_UPDATE = `UPDATE`
const EVENT_END = `END`
const EVENT_ERROR = `ERROR`

const PREVIEW_START = `PREVIEW:START`
const PREVIEW_PROGRESS = `PREVIEW:PROGRESS`
const PREVIEW_ERROR = `PREVIEW:ERROR`
const PREVIEW_END = `PREVIEW:END`

module.exports = {
  EVENT_START,
  EVENT_UPDATE,
  EVENT_END,
  EVENT_ERROR,

  PREVIEW_START,
  PREVIEW_PROGRESS,
  PREVIEW_END,
  PREVIEW_ERROR,
}
