/**
 * @jest-environment jsdom
 */
'use strict';

/**
 * Acceptance tests of the AI panel (epic #1177): the AI icons on the fields an
 * AI action fills.
 *
 * Seam: a function that places the icons in the editor's DOM. The subject
 * field has a label row of its own; the preheader field is generated by Mosaico
 * with no slot per property, so its icon is placed next to the input bound to
 * `preheaderText` (ADR 0004).
 */

const SUBJECT_FIELD = `
  <div class="email-metadata__field">
    <div class="email-metadata__label-row"><label for="email-metadata-subject">Objet de l'email</label></div>
    <input id="email-metadata-subject" type="text">
  </div>`;

const PREHEADER_FIELD = `
  <div class="propEditor">
    <span class="propLabel"><span>Preheader</span></span>
    <div class="propInput"><label class="data-text">
      <input type="text" data-bind="value: preheaderText, focusable: true">
    </label></div>
  </div>`;

const OTHER_FIELD = `
  <div class="propEditor">
    <span class="propLabel"><span>Brand</span></span>
    <div class="propInput"><input type="text" data-bind="value: brandText"></div>
  </div>`;

function render(html) {
  document.body.innerHTML = html;
  return document.body;
}

describe('ai panel: AI icons on the fields', () => {
  let placeFieldIcons;

  beforeAll(() => {
    ({
      placeFieldIcons,
    } = require('../../../packages/editor/src/js/ext/ai-panel/field-icons'));
  });

  const icons = (root) => [...root.querySelectorAll('[data-ai-target]')];
  const always = () => ({ actions: [{ id: 'x' }], opens: 'action' });

  it('places an icon in the label row of the subject field and next to the preheader field', () => {
    const root = render(SUBJECT_FIELD + PREHEADER_FIELD + OTHER_FIELD);
    placeFieldIcons(root, { actionsFor: always, onOpen: jest.fn() });
    expect(icons(root).map((icon) => icon.dataset.aiTarget)).toEqual([
      'subject',
      'preheader',
    ]);
    expect(
      root.querySelector(
        '.email-metadata__label-row [data-ai-target="subject"]'
      )
    ).not.toBeNull();
    expect(
      root.querySelector('.propEditor .propLabel [data-ai-target="preheader"]')
    ).not.toBeNull();
  });

  it('places no icon on a field whose target offers no action', () => {
    const root = render(SUBJECT_FIELD + PREHEADER_FIELD);
    placeFieldIcons(root, {
      actionsFor: () => ({ actions: [], opens: 'none' }),
      onOpen: jest.fn(),
    });
    expect(icons(root)).toEqual([]);
  });

  it('places no preheader icon when the template has no preheader field', () => {
    const root = render(SUBJECT_FIELD + OTHER_FIELD);
    placeFieldIcons(root, { actionsFor: always, onOpen: jest.fn() });
    expect(icons(root).map((icon) => icon.dataset.aiTarget)).toEqual([
      'subject',
    ]);
  });

  it('never places the same icon twice when called again', () => {
    const root = render(SUBJECT_FIELD + PREHEADER_FIELD);
    placeFieldIcons(root, { actionsFor: always, onOpen: jest.fn() });
    placeFieldIcons(root, { actionsFor: always, onOpen: jest.fn() });
    expect(icons(root)).toHaveLength(2);
  });

  it('names each icon after what it opens, right after its label', () => {
    const root = render(SUBJECT_FIELD + PREHEADER_FIELD);
    placeFieldIcons(root, {
      actionsFor: always,
      onOpen: jest.fn(),
      labelFor: (kind) => `Générer : ${kind}`,
    });
    const subject = root.querySelector('[data-ai-target="subject"]');
    expect(subject.getAttribute('aria-label')).toBe('Générer : subject');
    expect(subject.previousElementSibling.tagName).toBe('LABEL');
    expect(
      root
        .querySelector('[data-ai-target="preheader"]')
        .getAttribute('aria-label')
    ).toBe('Générer : preheader');
  });

  it('opens its target on click, and is a labelled button', () => {
    const onOpen = jest.fn();
    const root = render(PREHEADER_FIELD);
    placeFieldIcons(root, { actionsFor: always, onOpen });
    const icon = root.querySelector('[data-ai-target="preheader"]');
    expect(icon.tagName).toBe('BUTTON');
    expect(icon.getAttribute('type')).toBe('button');
    expect(icon.getAttribute('aria-label')).toBeTruthy();
    icon.click();
    expect(onOpen).toHaveBeenCalledWith({ kind: 'preheader' });
  });
});
