export const ERROR_CODES = {
  WORKSPACE_ALREADY_EXISTS: 'WORKSPACE_ALREADY_EXISTS',
  FORBIDDEN_WORKSPACE_CREATION: 'FORBIDDEN_WORKSPACE_CREATION',
  NOT_AUTHORIZED_ESP: 'NOT_AUTHORIZED_ESP',
  ESP_PROVIDER_INSTANCE_NOT_DEFINED: 'ESP_PROVIDER_INSTANCE_NOT_DEFINED',
  API_PROVIDER_NOT_DEFINED: 'API_PROVIDER_NOT_DEFINED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Taxonomy — KEEP IN SYNC with packages/server/constant/error-codes.js
  TAXONOMY_ITEM_NOT_FOUND: 'TAXONOMY_ITEM_NOT_FOUND',
  TAXONOMY_ITEM_LABEL_ALREADY_EXISTS: 'TAXONOMY_ITEM_LABEL_ALREADY_EXISTS',
  TAXONOMY_ITEM_IN_USE: 'TAXONOMY_ITEM_IN_USE',
  TAXONOMY_LIMIT_REACHED: 'TAXONOMY_LIMIT_REACHED',
  INVALID_TAXONOMY_ITEM: 'INVALID_TAXONOMY_ITEM',
  EMAIL_METADATA_DISABLED: 'EMAIL_METADATA_DISABLED',
  INVALID_EMAIL_METADATA: 'INVALID_EMAIL_METADATA',
};
