export const ERROR_CODES = {
  WORKSPACE_ALREADY_EXISTS: 'WORKSPACE_ALREADY_EXISTS',
  FORBIDDEN_WORKSPACE_CREATION: 'FORBIDDEN_WORKSPACE_CREATION',
  NOT_AUTHORIZED_ESP: 'NOT_AUTHORIZED_ESP',
  ESP_PROVIDER_INSTANCE_NOT_DEFINED: 'ESP_PROVIDER_INSTANCE_NOT_DEFINED',
  API_PROVIDER_NOT_DEFINED: 'API_PROVIDER_NOT_DEFINED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
};
